In [1]:
from pymongo import MongoClient
from pymongo.server_api import ServerApi
from werkzeug.security import generate_password_hash

import pandas as pd

import tqdm

In [2]:
users = pd.read_csv('../../Data/raw/users.csv')
ratings = pd.read_csv('../../Data/transformed/ratings_cleaned.csv')
movies = pd.read_csv('../../Data/transformed/movies_cleaned.csv')

In [3]:
merged = ratings.merge(movies, on='movieId')
# Extraer solo las columnas de géneros
genero_cols = movies.columns[3:-1]

def obtener_generos(row):
    return [genero for genero in genero_cols if row[genero] == 1]

merged['generos'] = merged.apply(obtener_generos, axis=1)
merged

,userId,movieId,rating,timestamp,title,Action,Adventure,Animation,Children's,Comedy,...,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year,generos
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),0,0,0,0,0,...,0,0,0,0,0,0,0,0,1975,[Drama]
1,1,661,3,978302109,James and the Giant Peach (1996),0,0,1,1,0,...,0,1,0,0,0,0,0,0,1996,"[Animation, Children's, Musical]"
2,1,914,3,978301968,My Fair Lady (1964),0,0,0,0,0,...,0,1,0,1,0,0,0,0,1964,"[Musical, Romance]"
3,1,3408,4,978300275,Erin Brockovich (2000),0,0,0,0,0,...,0,0,0,0,0,0,0,0,2000,[Drama]
4,1,2355,5,978824291,"Bug's Life, A (1998)",0,0,1,1,1,...,0,0,0,0,0,0,0,0,1998,"[Animation, Children's, Comedy]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000204,6040,1091,1,956716541,Weekend at Bernie's (1989),0,0,0,0,1,...,0,0,0,0,0,0,0,0,1989,[Comedy]
1000205,6040,1094,5,956704887,"Crying Game, The (1992)",0,0,0,0,0,...,0,0,0,1,0,0,1,0,1992,"[Drama, Romance, War]"
1000206,6040,562,5,956704746,Welcome to the Dollhouse (1995),0,0,0,0,1,...,0,0,0,0,0,0,0,0,1995,"[Comedy, Drama]"
1000207,6040,1096,4,956715648,Sophie's Choice (1982),0,0,0,0,0,...,0,0,0,0,0,0,0,0,1982,[Drama]
1000208,6040,1097,4,956715569,E.T. the Extra-Terrestrial (1982),0,0,0,1,0,...,0,0,0,0,1,0,0,0,1982,"[Children's, Drama, Fantasy, Sci-Fi]"

In [4]:
DB_NAME = 'Recomendaciones'
COLLECTION = 'usuarios'

uri = "mongodb+srv://AlumnoLinkia:holi1234@sistemarecomendacion.wqyrle5.mongodb.net/?retryWrites=true&w=majority&appName=SistemaRecomendacion"

In [6]:
client = MongoClient(uri, server_api=ServerApi('1'))
db = client[DB_NAME]
usuarios_col = db[COLLECTION]

In [6]:
def insertar_usuario(user_id, df_usuario, contrasena):
    peliculas = []
    for _, row in df_usuario.iterrows():
        peliculas.append({
            'movieId': row['movieId'],
            'pelicula': row['title'],
            'rating': row['rating'],
            'generos': row['generos'],
            'year': row['year']
        })

    usuario = {
        'numero': str(user_id),
        'contrasena': generate_password_hash(contrasena),
        'peliculas': peliculas
    }

    usuarios_col.insert_one(usuario)
    return usuario

In [7]:
for user_id, df_usuario in tqdm.tqdm(merged.groupby('userId')):
    contrasena = f"123qwe"
    insertar_usuario(user_id, df_usuario, contrasena)

100%|██████████| 6040/6040 [12:42<00:00,  7.93it/s]

In [9]:
COLLECTION = 'peliculas'
peliculas_col = db[COLLECTION]

In [10]:
genero_cols = movies.columns[3:-1]

def obtener_generos(row):
    return [genero for genero in genero_cols if row[genero] == 1]

movies['generos'] = movies.apply(obtener_generos, axis=1)
movies

,movieId,title,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,...,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year,generos
0,1,Toy Story (1995),0,0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,1995,"[Animation, Children's, Comedy]"
1,2,Jumanji (1995),0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1995,"[Adventure, Children's, Fantasy]"
2,3,Grumpier Old Men (1995),0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1995,"[Comedy, Romance]"
3,4,Waiting to Exhale (1995),0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1995,"[Comedy, Drama]"
4,5,Father of the Bride Part II (1995),0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1995,[Comedy]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,3948,Meet the Parents (2000),0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,2000,[Comedy]
3879,3949,Requiem for a Dream (2000),0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,2000,[Drama]
3880,3950,Tigerland (2000),0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,2000,[Drama]
3881,3951,Two Family House (2000),0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,2000,[Drama]
3882,3952,"Contender, The (2000)",0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,2000,"[Drama, Thriller]"

In [19]:
def insertar_pelicula(df, index):
    pelicula = {
        'movieId': str(df.loc[index, 'movieId']),
        'title': df.loc[index, 'title'],
        'year': str(df.loc[index, 'year']),
        'generos': df.loc[index, 'generos']
    }
    
    peliculas_col.insert_one(pelicula)

In [20]:
for idx in tqdm.tqdm(movies.index):
    insertar_pelicula(movies, idx)

100%|██████████| 3883/3883 [02:29<00:00, 25.96it/s]