In [85]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import optuna
from surprise import Dataset, Reader, KNNBasic, SVD, accuracy
from surprise.model_selection import train_test_split as train_test_split_surprise
from surprise.model_selection import cross_validate
from surprise.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split as train_test_split_sklearn

In [86]:
point = (
    '../data/raw/movies.csv'
)
datos_movies = pd.read_csv(point, sep=',')
datos_movies.head(3)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance

In [87]:
point = (
    '../data/raw/ratings.csv'
)
datos_ratings = pd.read_csv(point, sep=',')
datos_ratings.head(3)

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246

In [88]:
datos_movies["genres"] = datos_movies["genres"].str.split("|")

df_exploded = datos_movies.explode('genres')
genre_dummies = pd.get_dummies(df_exploded['genres'])

df_combined = pd.concat([df_exploded[['movieId', 'title']], genre_dummies], axis=1)

In [89]:
df_final_movies = df_combined.groupby(['movieId', 'title'], as_index=False).sum()

In [90]:
df_final_movies

,movieId,title,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),0,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
4,5,Father of the Bride Part II (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10324,146684,Cosmic Scrat-tastrophe (2015),0,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
10325,146878,Le Grand Restaurant (1966),0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
10326,148238,A Very Murray Christmas (2015),0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
10327,148626,The Big Short (2015),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10328,149532,Marco Polo: One Hundred Eyes (2015),1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [91]:
df = merged_data = pd.merge(
    datos_ratings,
    df_final_movies,
    on="movieId",
    how="right"
)
df.head()

,userId,movieId,rating,timestamp,title,(no genres listed),Action,Adventure,Animation,Children,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,2.0,1,5.0,8.590469e+08,Toy Story (1995),0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,5.0,1,4.0,1.303501e+09,Toy Story (1995),0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,8.0,1,5.0,8.586109e+08,Toy Story (1995),0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,11.0,1,4.0,8.508158e+08,Toy Story (1995),0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,14.0,1,4.0,8.517663e+08,Toy Story (1995),0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [92]:
df['year'] = df['title'].str.rsplit('(', n=1).str[-1].str.replace(')', '')
df['title'] = df['title'].str.rsplit('(', n=1).str[0].str.strip()

df['year'] = df['year'].where(df['year'].str.isnumeric(), None).astype('Int64')

print(df)

        userId  movieId  rating     timestamp                         title  \
0          2.0        1     5.0  8.590469e+08                     Toy Story
1          5.0        1     4.0  1.303501e+09                     Toy Story
2          8.0        1     5.0  8.586109e+08                     Toy Story
3         11.0        1     4.0  8.508158e+08                     Toy Story
4         14.0        1     4.0  8.517663e+08                     Toy Story
...        ...      ...     ...           ...                           ...
105338   475.0   148238     3.0  1.451213e+09       A Very Murray Christmas
105339   458.0   148626     4.0  1.452015e+09                 The Big Short
105340   576.0   148626     4.5  1.451688e+09                 The Big Short
105341   668.0   148626     4.5  1.451148e+09                 The Big Short
105342   475.0   149532     4.0  1.451223e+09  Marco Polo: One Hundred Eyes

        (no genres listed)  Action  Adventure  Animation  Children  ...  \
0                        0       0          1          1         1  ...
1                        0       0          1          1         1  ...
2                        0       0          1          1         1  ...
3                        0       0          1          1         1  ...
4                        0       0          1          1         1  ...
...                    ...     ...        ...        ...       ...  ...
105338                   0       0          0          0         0  ...
105339                   0       0          0          0         0  ...
105340                   0       0          0          0         0  ...
105341                   0       0          0          0         0  ...
105342                   1       0          0          0         0  ...

        Horror  IMAX  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
0            0     0        0        0        0       0         0    0
1            0     0        0        0        0       0         0    0
2            0     0        0        0        0       0         0    0
3            0     0        0        0        0       0         0    0
4            0     0        0        0        0       0         0    0
...        ...   ...      ...      ...      ...     ...       ...  ...
105338       0     0        0        0        0       0         0    0
105339       0     0        0        0        0       0         0    0
105340       0     0        0        0        0       0         0    0
105341       0     0        0        0        0       0         0    0
105342       0     0        0        0        0       0         0    0

        Western  year
0             0  1995
1             0  1995
2             0  1995
3             0  1995
4             0  1995
...         ...   ...
105338        0  2015
105339        0  2015
105340        0  2015
105341        0  2015
105342        0  2015

[105343 rows x 26 columns]

In [93]:
df = df.dropna()  # axis=0 por defecto
print(df.isna().sum())

userId                0
movieId               0
rating                0
timestamp             0
title                 0
(no genres listed)    0
Action                0
Adventure             0
Animation             0
Children              0
Comedy                0
Crime                 0
Documentary           0
Drama                 0
Fantasy               0
Film-Noir             0
Horror                0
IMAX                  0
Musical               0
Mystery               0
Romance               0
Sci-Fi                0
Thriller              0
War                   0
Western               0
year                  0
dtype: int64

In [94]:
datos_ratings['userId'].nunique()

668

In [95]:
df_colab  = datos_ratings.groupby('movieId')['rating'].mean().reset_index()

# opcional: renombrar la columna para mayor claridad
mean_ratings = df_colab.rename(columns={'rating': 'rating_medio'})

mean_ratings.head(20)

    movieId  rating_medio
0         1      3.907328
1         2      3.353261
2         3      3.189655
3         4      2.818182
4         5      3.250000
5         6      4.073913
6         7      3.381818
7         8      3.666667
8         9      2.869565
9        10      3.600000
10       11      3.729412
11       12      2.825000
12       13      3.437500
13       14      3.460000
14       15      3.111111
15       16      3.785714
16       17      3.930000
17       18      3.642857
18       19      2.642857
19       20      3.156250

In [96]:
X = mean_ratings
y = mean_ratings

In [97]:
#df_finito = df[['userId', 'movieId', 'rating']]
reader = Reader(rating_scale=(1, 5))
df_finito = Dataset.load_from_df(df[['userId', 'movieId', 'rating']], reader)

In [98]:
trainset, testset = train_test_split_surprise(df_finito, test_size=0.2, random_state=42)

In [99]:
df_finito

In [100]:
def objective(trial):
    n_factors = trial.suggest_int('n_factors', 20, 200)
    reg_all = trial.suggest_float('reg_all', 0.001, 0.1, log=True)
    lr_all = trial.suggest_float('lr_all', 0.001, 0.1, log=True)

    model = SVD(n_factors=n_factors, reg_all=reg_all, lr_all=lr_all)
    cross_val_result = cross_validate(model, df_finito, measures=['RMSE'], cv=5, verbose=False)

    return cross_val_result['test_rmse'].mean()

In [101]:
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=50)
best_params = study.best_params

[I 2025-05-23 19:16:24,769] A new study created in memory with name: no-name-9d9a5c6c-f835-4e06-b10a-9322dde183d6
[I 2025-05-23 19:16:31,934] Trial 0 finished with value: 0.8817718156983118 and parameters: {'n_factors': 115, 'reg_all': 0.09920075541894038, 'lr_all': 0.001701317562372154}. Best is trial 0 with value: 0.8817718156983118.
[I 2025-05-23 19:16:38,598] Trial 1 finished with value: 0.8757676385367986 and parameters: {'n_factors': 143, 'reg_all': 0.015785391006111232, 'lr_all': 0.04819393191402378}. Best is trial 1 with value: 0.8757676385367986.
[I 2025-05-23 19:16:42,197] Trial 2 finished with value: 0.8864964822485888 and parameters: {'n_factors': 20, 'reg_all': 0.05469104535968797, 'lr_all': 0.039012824087632965}. Best is trial 1 with value: 0.8757676385367986.
[I 2025-05-23 19:16:47,965] Trial 3 finished with value: 0.8850117038948822 and parameters: {'n_factors': 116, 'reg_all': 0.018158695732527184, 'lr_all': 0.023398166189817268}. Best is trial 1 with value: 0.8757676385367986.
[I 2025-05-23 19:16:51,857] Trial 4 finished with value: 0.981479307475334 and parameters: {'n_factors': 32, 'reg_all': 0.0052422024856422535, 'lr_all': 0.028035119093668667}. Best is trial 1 with value: 0.8757676385367986.
[I 2025-05-23 19:16:59,487] Trial 5 finished with value: 0.8872681949713919 and parameters: {'n_factors': 195, 'reg_all': 0.007467007218285918, 'lr_all': 0.00199076245152973}. Best is trial 1 with value: 0.8757676385367986.
[I 2025-05-23 19:17:03,724] Trial 6 finished with value: 1.0408105080670602 and parameters: {'n_factors': 48, 'reg_all': 0.0010722283082758505, 'lr_all': 0.07523886444299224}. Best is trial 1 with value: 0.8757676385367986.
[I 2025-05-23 19:17:10,834] Trial 7 finished with value: 0.8517693778306477 and parameters: {'n_factors': 164, 'reg_all': 0.07159889171768373, 'lr_all': 0.016064024687414906}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:17:17,091] Trial 8 finished with value: 0.8921188437617917 and parameters: {'n_factors': 138, 'reg_all': 0.007729137481265839, 'lr_all': 0.0012379296094065207}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:17:23,813] Trial 9 finished with value: 0.9549620679161859 and parameters: {'n_factors': 86, 'reg_all': 0.0018117940315321777, 'lr_all': 0.05355700675451703}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:17:31,396] Trial 10 finished with value: 0.8620726437958641 and parameters: {'n_factors': 199, 'reg_all': 0.0568970431190829, 'lr_all': 0.00611470625161324}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:17:39,167] Trial 11 finished with value: 0.8633570410776293 and parameters: {'n_factors': 200, 'reg_all': 0.038701836137520415, 'lr_all': 0.006652555706585481}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:17:46,175] Trial 12 finished with value: 0.8597807225573316 and parameters: {'n_factors': 170, 'reg_all': 0.09538220916728266, 'lr_all': 0.007845388698355339}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:17:53,036] Trial 13 finished with value: 0.8526953455075252 and parameters: {'n_factors': 165, 'reg_all': 0.0999111724560114, 'lr_all': 0.012837739151098527}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:18:00,613] Trial 14 finished with value: 0.8699927827827277 and parameters: {'n_factors': 161, 'reg_all': 0.02750431259612265, 'lr_all': 0.012256134516204262}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:18:05,885] Trial 15 finished with value: 0.8602433453854939 and parameters: {'n_factors': 86, 'reg_all': 0.053654373672266956, 'lr_all': 0.016734622088414097}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:18:12,886] Trial 16 finished with value: 0.8877095571801622 and parameters: {'n_factors': 168, 'reg_all': 0.003638506925077401, 'lr_all': 0.0036306859568698718}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:18:19,022] Trial 17 finished with value: 0.874917960964057 and parameters: {'n_factors': 134, 'reg_all': 0.02423129951754184, 'lr_all': 0.013215064098097931}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:18:27,216] Trial 18 finished with value: 0.8675225330300289 and parameters: {'n_factors': 156, 'reg_all': 0.09957033870577243, 'lr_all': 0.004023087591291226}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:18:34,764] Trial 19 finished with value: 0.8853678146150991 and parameters: {'n_factors': 180, 'reg_all': 0.013358005305313933, 'lr_all': 0.022601673759687566}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:18:40,026] Trial 20 finished with value: 0.8614745887355431 and parameters: {'n_factors': 90, 'reg_all': 0.036618882091028905, 'lr_all': 0.00943498585418112}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:18:47,518] Trial 21 finished with value: 0.8590319169016304 and parameters: {'n_factors': 178, 'reg_all': 0.08106036944155012, 'lr_all': 0.007396525964925178}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:18:54,542] Trial 22 finished with value: 0.8663237415650379 and parameters: {'n_factors': 176, 'reg_all': 0.050888391679811594, 'lr_all': 0.004729972005146478}. Best is trial 7 with value: 0.8517693778306477.
[I 2025-05-23 19:19:01,025] Trial 23 finished with value: 0.8512814790869119 and parameters: {'n_factors': 150, 'reg_all': 0.0640559322932605, 'lr_all': 0.016236347069322084}. Best is trial 23 with value: 0.8512814790869119.
[I 2025-05-23 19:19:07,536] Trial 24 finished with value: 0.852403827416442 and parameters: {'n_factors': 146, 'reg_all': 0.06550994417948063, 'lr_all': 0.01647597715330816}. Best is trial 23 with value: 0.8512814790869119.
[I 2025-05-23 19:19:14,008] Trial 25 finished with value: 0.8668845282554972 and parameters: {'n_factors': 147, 'reg_all': 0.031312593815413264, 'lr_all': 0.01763865131354495}. Best is trial 23 with value: 0.8512814790869119.
[I 2025-05-23 19:19:20,281] Trial 26 finished with value: 0.8549812597791355 and parameters: {'n_factors': 126, 'reg_all': 0.06795503264326094, 'lr_all': 0.032550015882905396}. Best is trial 23 with value: 0.8512814790869119.
[I 2025-05-23 19:19:26,256] Trial 27 finished with value: 0.8831606921015934 and parameters: {'n_factors': 103, 'reg_all': 0.020860782187477698, 'lr_all': 0.09349256568173939}. Best is trial 23 with value: 0.8512814790869119.
[I 2025-05-23 19:19:34,799] Trial 28 finished with value: 0.8604313871710658 and parameters: {'n_factors': 148, 'reg_all': 0.040657450964640324, 'lr_all': 0.01893571293356876}. Best is trial 23 with value: 0.8512814790869119.
[I 2025-05-23 19:19:40,744] Trial 29 finished with value: 0.8733033053711863 and parameters: {'n_factors': 124, 'reg_all': 0.06400099731311322, 'lr_all': 0.002806015097061323}. Best is trial 23 with value: 0.8512814790869119.
[I 2025-05-23 19:19:46,332] Trial 30 finished with value: 0.896295045160306 and parameters: {'n_factors': 104, 'reg_all': 0.011663112701901004, 'lr_all': 0.01127248425355807}. Best is trial 23 with value: 0.8512814790869119.
[I 2025-05-23 19:19:53,181] Trial 31 finished with value: 0.8512456449360734 and parameters: {'n_factors': 157, 'reg_all': 0.07874223325635427, 'lr_all': 0.014772229935809785}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:19:59,778] Trial 32 finished with value: 0.8518349260896905 and parameters: {'n_factors': 154, 'reg_all': 0.07326796334749136, 'lr_all': 0.01564704197494932}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:20:07,050] Trial 33 finished with value: 0.8581269324251954 and parameters: {'n_factors': 185, 'reg_all': 0.04449455362023547, 'lr_all': 0.039942898073542885}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:20:14,167] Trial 34 finished with value: 0.8520749336433433 and parameters: {'n_factors': 157, 'reg_all': 0.07007475188016615, 'lr_all': 0.0255948071171676}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:20:20,258] Trial 35 finished with value: 0.8555722939351054 and parameters: {'n_factors': 130, 'reg_all': 0.0767318670342525, 'lr_all': 0.009656803284960314}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:20:26,834] Trial 36 finished with value: 0.8772076924519838 and parameters: {'n_factors': 154, 'reg_all': 0.017229027419021443, 'lr_all': 0.03322778858255988}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:20:34,013] Trial 37 finished with value: 0.8626396609488223 and parameters: {'n_factors': 187, 'reg_all': 0.03326967224309188, 'lr_all': 0.02112677608452319}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:20:41,488] Trial 38 finished with value: 0.8645513097319906 and parameters: {'n_factors': 118, 'reg_all': 0.04824178135373648, 'lr_all': 0.05109155630599384}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:20:48,064] Trial 39 finished with value: 0.9251629693223883 and parameters: {'n_factors': 140, 'reg_all': 0.003013512503378682, 'lr_all': 0.01448608778259207}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:20:55,314] Trial 40 finished with value: 0.852186407336832 and parameters: {'n_factors': 172, 'reg_all': 0.07883865522352804, 'lr_all': 0.02815742229367112}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:21:01,834] Trial 41 finished with value: 0.8554803090494477 and parameters: {'n_factors': 156, 'reg_all': 0.06280017427111129, 'lr_all': 0.024920786061321875}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:21:06,300] Trial 42 finished with value: 0.8567655394729659 and parameters: {'n_factors': 57, 'reg_all': 0.0801300773258015, 'lr_all': 0.009464262759271386}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:21:13,050] Trial 43 finished with value: 0.8578783932677789 and parameters: {'n_factors': 160, 'reg_all': 0.04670282188402591, 'lr_all': 0.0394823675171907}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:21:19,426] Trial 44 finished with value: 0.8564315742215012 and parameters: {'n_factors': 140, 'reg_all': 0.056951075983314156, 'lr_all': 0.02646152185172809}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:21:26,938] Trial 45 finished with value: 0.8703399186600242 and parameters: {'n_factors': 189, 'reg_all': 0.026397892862021717, 'lr_all': 0.015177755026751498}. Best is trial 31 with value: 0.8512456449360734.
[I 2025-05-23 19:21:33,735] Trial 46 finished with value: 0.8507141394732681 and parameters: {'n_factors': 152, 'reg_all': 0.08440428508436588, 'lr_all': 0.020435084625659756}. Best is trial 46 with value: 0.8507141394732681.
[I 2025-05-23 19:21:41,974] Trial 47 finished with value: 0.8644783509393358 and parameters: {'n_factors': 150, 'reg_all': 0.08440622717475778, 'lr_all': 0.005379200819713118}. Best is trial 46 with value: 0.8507141394732681.
[I 2025-05-23 19:21:49,070] Trial 48 finished with value: 0.8511453978262576 and parameters: {'n_factors': 166, 'reg_all': 0.0980039812184859, 'lr_all': 0.019696739687206644}. Best is trial 46 with value: 0.8507141394732681.
[I 2025-05-23 19:21:56,012] Trial 49 finished with value: 0.8519402365953133 and parameters: {'n_factors': 169, 'reg_all': 0.09903798519642054, 'lr_all': 0.020096684319320025}. Best is trial 46 with value: 0.8507141394732681.

In [109]:
#Aun no he configurado para que traiga los mejores parametros
sim_options = {'name': 'cosine', 'user_based': True}  # Cambia user_based=True para KNN de usuarios
model = SVD(n_factors=best_params['n_factors'], reg_all=best_params['reg_all'], lr_all=best_params['lr_all'])  # Esta linea dedicada para ajustar el consumo de RAM
#model = KNNBasic(sim_options=sim_options) #Errores por tamaño de dataset
model.fit(trainset)

predictions = model.test(testset)#predecimos

In [103]:
rmse = accuracy.rmse(predictions)
print(f'RMSE: {rmse}')

RMSE: 0.8676
RMSE: 0.8675856227938576

In [104]:

user = str(96737)  # IDs deben ser strings en Surprise.... por alguna razón 
item = str(242)
pred = model.predict(user, item)
print(f'Predicción  {user} para peli {item}',pred)

Predicción  96737 para peli 242 user: 96737      item: 242        r_ui = None   est = 3.52   {'was_impossible': False}

In [105]:
predictions

[Prediction(uid=198.0, iid=2971, r_ui=3.0, est=4.050205531012718, details={'was_impossible': False}),
 Prediction(uid=192.0, iid=3148, r_ui=4.0, est=3.8223623225283543, details={'was_impossible': False}),
 Prediction(uid=96.0, iid=736, r_ui=3.0, est=2.6629921971989887, details={'was_impossible': False}),
 Prediction(uid=615.0, iid=1645, r_ui=4.0, est=3.8051821845596376, details={'was_impossible': False}),
 Prediction(uid=140.0, iid=1006, r_ui=2.0, est=2.934218813594623, details={'was_impossible': False}),
 Prediction(uid=164.0, iid=1485, r_ui=4.0, est=3.7694707646642467, details={'was_impossible': False}),
 Prediction(uid=387.0, iid=64969, r_ui=4.0, est=3.8821876392611316, details={'was_impossible': False}),
 Prediction(uid=668.0, iid=282, r_ui=3.5, est=2.839163551552413, details={'was_impossible': False}),
 Prediction(uid=434.0, iid=60069, r_ui=1.5, est=3.8293827788226946, details={'was_impossible': False}),
 Prediction(uid=567.0, iid=2021, r_ui=2.5, est=3.3684555235141524, details={'was_impossible': False}),
 Prediction(uid=177.0, iid=3911, r_ui=4.5, est=3.48542509620482, details={'was_impossible': False}),
 Prediction(uid=244.0, iid=1581, r_ui=2.0, est=2.7506046300868294, details={'was_impossible': False}),
 Prediction(uid=128.0, iid=79428, r_ui=3.5, est=3.166334075127203, details={'was_impossible': False}),
 Prediction(uid=618.0, iid=1629, r_ui=2.0, est=2.91577781695089, details={'was_impossible': False}),
 Prediction(uid=219.0, iid=4240, r_ui=1.0, est=3.0933954673279542, details={'was_impossible': False}),
 Prediction(uid=184.0, iid=2716, r_ui=5.0, est=3.803982374134492, details={'was_impossible': False}),
 Prediction(uid=32.0, iid=1185, r_ui=4.0, est=4.214254952910894, details={'was_impossible': False}),
 Prediction(uid=107.0, iid=996, r_ui=2.0, est=3.1776696270333478, details={'was_impossible': False}),
 Prediction(uid=505.0, iid=1569, r_ui=5.0, est=3.6810739150731187, details={'was_impossible': False}),
 Prediction(uid=177.0, iid=2005, r_ui=3.0, est=3.177197420246428, details={'was_impossible': False}),
 Prediction(uid=568.0, iid=6773, r_ui=4.5, est=3.8974030289412394, details={'was_impossible': False}),
 Prediction(uid=189.0, iid=347, r_ui=4.0, est=4.112319565331124, details={'was_impossible': False}),
 Prediction(uid=556.0, iid=761, r_ui=4.0, est=3.608158539800358, details={'was_impossible': False}),
 Prediction(uid=555.0, iid=1270, r_ui=5.0, est=4.394234657283914, details={'was_impossible': False}),
 Prediction(uid=530.0, iid=42018, r_ui=3.0, est=2.928227335420237, details={'was_impossible': False}),
 Prediction(uid=304.0, iid=1198, r_ui=3.5, est=3.9546923623743986, details={'was_impossible': False}),
 Prediction(uid=235.0, iid=2539, r_ui=2.0, est=3.309689810393445, details={'was_impossible': False}),
 Prediction(uid=650.0, iid=1197, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=478.0, iid=58047, r_ui=4.0, est=3.696724866877511, details={'was_impossible': False}),
 Prediction(uid=232.0, iid=5501, r_ui=3.0, est=3.5199219896612535, details={'was_impossible': False}),
 Prediction(uid=122.0, iid=4896, r_ui=4.0, est=3.7680639163278635, details={'was_impossible': False}),
 Prediction(uid=244.0, iid=2243, r_ui=4.0, est=3.122017329785559, details={'was_impossible': False}),
 Prediction(uid=118.0, iid=2707, r_ui=4.0, est=3.4486558231271367, details={'was_impossible': False}),
 Prediction(uid=224.0, iid=52950, r_ui=3.5, est=3.341512858091518, details={'was_impossible': False}),
 Prediction(uid=451.0, iid=546, r_ui=1.5, est=2.407886020563879, details={'was_impossible': False}),
 Prediction(uid=395.0, iid=4370, r_ui=1.0, est=3.5519997843416515, details={'was_impossible': False}),
 Prediction(uid=666.0, iid=2433, r_ui=2.0, est=3.1839096828197913, details={'was_impossible': False}),
 Prediction(uid=60.0, iid=2109, r_ui=3.5, est=3.5370055298028373, details={'was_impossible': False}),
 Prediction(uid=561.0, iid=39, r_ui=3.0, est=3.4777380555824866, details={'was_impossible': False}),
 Prediction(uid=443.0, iid=1267, r_ui=5.0, est=4.2868946432101875, details={'was_impossible': False}),
 Prediction(uid=164.0, iid=2723, r_ui=3.0, est=3.407644700492259, details={'was_impossible': False}),
 Prediction(uid=352.0, iid=858, r_ui=4.0, est=3.8724163297702305, details={'was_impossible': False}),
 Prediction(uid=534.0, iid=235, r_ui=2.0, est=3.684442041123675, details={'was_impossible': False}),
 Prediction(uid=399.0, iid=2672, r_ui=1.0, est=3.247143219991702, details={'was_impossible': False}),
 Prediction(uid=109.0, iid=500, r_ui=4.0, est=3.9325415667264396, details={'was_impossible': False}),
 Prediction(uid=627.0, iid=1391, r_ui=4.0, est=3.002132572300047, details={'was_impossible': False}),
 Prediction(uid=451.0, iid=5502, r_ui=2.0, est=3.487884810990948, details={'was_impossible': False}),
 Prediction(uid=438.0, iid=5296, r_ui=2.5, est=3.472173493996457, details={'was_impossible': False}),
 Prediction(uid=560.0, iid=5872, r_ui=4.0, est=3.8310205133737463, details={'was_impossible': False}),
 Prediction(uid=275.0, iid=2203, r_ui=4.5, est=3.476347532433608, details={'was_impossible': False}),
 Prediction(uid=224.0, iid=4855, r_ui=4.5, est=3.6422096693473653, details={'was_impossible': False}),
 Prediction(uid=374.0, iid=593, r_ui=4.5, est=4.104086351697859, details={'was_impossible': False}),
 Prediction(uid=63.0, iid=58301, r_ui=2.0, est=3.1130492919675445, details={'was_impossible': False}),
 Prediction(uid=160.0, iid=1952, r_ui=5.0, est=4.297909611903227, details={'was_impossible': False}),
 Prediction(uid=424.0, iid=413, r_ui=3.0, est=2.89744711557233, details={'was_impossible': False}),
 Prediction(uid=516.0, iid=4812, r_ui=3.0, est=3.361207501494256, details={'was_impossible': False}),
 Prediction(uid=71.0, iid=2671, r_ui=5.0, est=3.994664555659153, details={'was_impossible': False}),
 Prediction(uid=260.0, iid=17, r_ui=4.0, est=3.698421847830733, details={'was_impossible': False}),
 Prediction(uid=232.0, iid=76753, r_ui=3.5, est=3.880048834024418, details={'was_impossible': False}),
 Prediction(uid=244.0, iid=900, r_ui=5.0, est=2.931117311611067, details={'was_impossible': False}),
 Prediction(uid=628.0, iid=7156, r_ui=5.0, est=4.1164990097397105, details={'was_impossible': False}),
 Prediction(uid=340.0, iid=10, r_ui=3.0, est=3.0577847522724495, details={'was_impossible': False}),
 Prediction(uid=213.0, iid=3362, r_ui=4.0, est=4.013386931340242, details={'was_impossible': False}),
 Prediction(uid=461.0, iid=1020, r_ui=3.5, est=3.4136137627165293, details={'was_impossible': False}),
 Prediction(uid=528.0, iid=60069, r_ui=5.0, est=3.8652914510055116, details={'was_impossible': False}),
 Prediction(uid=315.0, iid=2402, r_ui=0.5, est=3.182625172228499, details={'was_impossible': False}),
 Prediction(uid=413.0, iid=6539, r_ui=4.0, est=3.636961831263621, details={'was_impossible': False}),
 Prediction(uid=244.0, iid=425, r_ui=3.0, est=2.76102176402541, details={'was_impossible': False}),
 Prediction(uid=22.0, iid=453, r_ui=2.0, est=3.190949744982396, details={'was_impossible': False}),
 Prediction(uid=668.0, iid=101112, r_ui=2.5, est=2.9115737299302853, details={'was_impossible': False}),
 Prediction(uid=458.0, iid=4978, r_ui=4.0, est=3.4012549852049814, details={'was_impossible': False}),
 Prediction(uid=331.0, iid=410, r_ui=4.0, est=3.029133071789867, details={'was_impossible': False}),
 Prediction(uid=228.0, iid=2231, r_ui=5.0, est=4.263341005553178, details={'was_impossible': False}),
 Prediction(uid=410.0, iid=2297, r_ui=3.5, est=2.7508982154733905, details={'was_impossible': False}),
 Prediction(uid=310.0, iid=1370, r_ui=2.0, est=3.0456920133242695, details={'was_impossible': False}),
 Prediction(uid=475.0, iid=61697, r_ui=1.5, est=3.3122984298041858, details={'was_impossible': False}),
 Prediction(uid=544.0, iid=2987, r_ui=2.0, est=3.8597643394510026, details={'was_impossible': False}),
 Prediction(uid=213.0, iid=1245, r_ui=4.0, est=4.319775589690973, details={'was_impossible': False}),
 Prediction(uid=376.0, iid=2424, r_ui=1.0, est=2.7237376071967727, details={'was_impossible': False}),
 Prediction(uid=458.0, iid=26729, r_ui=4.0, est=3.48184619309159, details={'was_impossible': False}),
 Prediction(uid=589.0, iid=2478, r_ui=4.5, est=3.772530073855401, details={'was_impossible': False}),
 Prediction(uid=475.0, iid=69134, r_ui=3.5, est=3.0922953056246136, details={'was_impossible': False}),
 Prediction(uid=575.0, iid=2642, r_ui=2.0, est=2.1566346269553014, details={'was_impossible': False}),
 Prediction(uid=315.0, iid=592, r_ui=4.0, est=3.333651679019116, details={'was_impossible': False}),
 Prediction(uid=5.0, iid=592, r_ui=0.5, est=3.20282281218422, details={'was_impossible': False}),
 Prediction(uid=668.0, iid=7106, r_ui=2.5, est=2.846143926478351, details={'was_impossible': False}),
 Prediction(uid=172.0, iid=4993, r_ui=5.0, est=4.060152747478717, details={'was_impossible': False}),
 Prediction(uid=17.0, iid=55995, r_ui=4.5, est=3.5038848072535576, details={'was_impossible': False}),
 Prediction(uid=126.0, iid=4963, r_ui=5.0, est=3.878640505939344, details={'was_impossible': False}),
 Prediction(uid=232.0, iid=6701, r_ui=4.0, est=3.880048834024418, details={'was_impossible': False}),
 Prediction(uid=38.0, iid=79428, r_ui=3.5, est=2.77557464345533, details={'was_impossible': False}),
 Prediction(uid=283.0, iid=828, r_ui=3.0, est=2.8839686685959953, details={'was_impossible': False}),
 Prediction(uid=177.0, iid=514, r_ui=2.0, est=3.194575741865279, details={'was_impossible': False}),
 Prediction(uid=109.0, iid=3999, r_ui=3.0, est=3.7194916344419027, details={'was_impossible': False}),
 Prediction(uid=480.0, iid=6440, r_ui=3.0, est=4.0733894438499485, details={'was_impossible': False}),
 Prediction(uid=38.0, iid=45499, r_ui=2.0, est=2.7716564922556204, details={'was_impossible': False}),
 Prediction(uid=615.0, iid=910, r_ui=4.0, est=4.342076973347824, details={'was_impossible': False}),
 Prediction(uid=255.0, iid=2422, r_ui=2.5, est=2.602598927683478, details={'was_impossible': False}),
 Prediction(uid=668.0, iid=25866, r_ui=3.5, est=2.846143926478351, details={'was_impossible': False}),
 Prediction(uid=303.0, iid=3147, r_ui=3.0, est=3.917615151927493, details={'was_impossible': False}),
 Prediction(uid=336.0, iid=1291, r_ui=4.0, est=3.8686880668247148, details={'was_impossible': False}),
 Prediction(uid=458.0, iid=25777, r_ui=4.5, est=3.490128500896921, details={'was_impossible': False}),
 Prediction(uid=469.0, iid=1304, r_ui=3.0, est=3.6879044210322056, details={'was_impossible': False}),
 Prediction(uid=330.0, iid=903, r_ui=5.0, est=4.717932652010716, details={'was_impossible': False}),
 Prediction(uid=668.0, iid=2166, r_ui=2.5, est=2.894583727200626, details={'was_impossible': False}),
 Prediction(uid=668.0, iid=31427, r_ui=2.0, est=2.741029943716937, details={'was_impossible': False}),
 Prediction(uid=189.0, iid=2125, r_ui=1.0, est=4.051813434522879, details={'was_impossible': False}),
 Prediction(uid=554.0, iid=2501, r_ui=4.5, est=4.151646451444539, details={'was_impossible': False}),
 Prediction(uid=275.0, iid=5499, r_ui=3.5, est=3.5698913033580633, details={'was_impossible': False}),
 Prediction(uid=615.0, iid=908, r_ui=4.0, est=4.471819304299772, details={'was_impossible': False}),
 Prediction(uid=569.0, iid=8529, r_ui=3.0, est=3.6068561220020916, details={'was_impossible': False}),
 Prediction(uid=63.0, iid=19, r_ui=3.0, est=2.433794927032035, details={'was_impossible': False}),
 Prediction(uid=66.0, iid=5525, r_ui=4.0, est=3.378474815843497, details={'was_impossible': False}),
 Prediction(uid=597.0, iid=1022, r_ui=4.0, est=3.674239519515092, details={'was_impossible': False}),
 Prediction(uid=668.0, iid=4518, r_ui=1.0, est=2.925809306448765, details={'was_impossible': False}),
 Prediction(uid=576.0, iid=140265, r_ui=4.5, est=3.6234515024568266, details={'was_impossible': False}),
 Prediction(uid=423.0, iid=595, r_ui=3.5, est=3.5403926815223867, details={'was_impossible': False}),
 Prediction(uid=668.0, iid=3152, r_ui=4.0, est=3.2700722457832962, details={'was_impossible': False}),
 Prediction(uid=128.0, iid=27584, r_ui=2.5, est=3.401080845227872, details={'was_impossible': False}),
 Prediction(uid=413.0, iid=95058, r_ui=1.5, est=3.3323395830785714, details={'was_impossible': False}),
 Prediction(uid=179.0, iid=2686, r_ui=4.5, est=3.1638288452723846, details={'was_impossible': False}),
 Prediction(uid=452.0, iid=2948, r_ui=3.0, est=3.691172858820398, details={'was_impossible': False}),
 Prediction(uid=134.0, iid=1357, r_ui=5.0, est=4.418827157030778, details={'was_impossible': False}),
 Prediction(uid=429.0, iid=4299, r_ui=5.0, est=3.15230468362844, details={'was_impossible': False}),
 Prediction(uid=211.0, iid=1252, r_ui=3.5, est=4.5698443901944845, details={'was_impossible': False}),
 Prediction(uid=531.0, iid=8361, r_ui=4.5, est=3.92754399649355, details={'was_impossible': False}),
 Prediction(uid=558.0, iid=11, r_ui=5.0, est=3.435972747866493, details={'was_impossible': False}),
 Prediction(uid=62.0, iid=1, r_ui=2.0, est=2.83739410953053, details={'was_impossible': False}),
 Prediction(uid=189.0, iid=2951, r_ui=4.5, est=4.216977287209711, details={'was_impossible': False}),
 Prediction(uid=218.0, iid=2732, r_ui=5.0, est=4.551866856674587, details={'was_impossible': False}),
 Prediction(uid=501.0, iid=48, r_ui=3.0, est=3.098126575895569, details={'was_impossible': False}),
 Prediction(uid=384.0, iid=1220, r_ui=4.0, est=3.9627095046337226, details={'was_impossible': False}),
 Prediction(uid=668.0, iid=2467, r_ui=4.0, est=3.0653867885290644, details={'was_impossible': False}),
 Prediction(uid=218.0, iid=2083, r_ui=4.0, est=4.169281539122166, details={'was_impossible': False}),
 Prediction(uid=255.0, iid=3578, r_ui=3.5, est=3.835646241989602, details={'was_impossible': False}),
 Prediction(uid=575.0, iid=55272, r_ui=2.5, est=3.2181256102016516, details={'was_impossible': False}),
 Prediction(uid=528.0, iid=780, r_ui=3.5, est=3.3602886838246744, details={'was_impossible': False}),
 Prediction(uid=336.0, iid=260, r_ui=1.5, est=3.787180842363574, details={'was_impossible': False}),
 Prediction(uid=668.0, iid=61451, r_ui=4.0, est=2.846143926478351, details={'was_impossible': False}),
 Prediction(uid=575.0, iid=3481, r_ui=4.0, est=3.665866182287501, details={'was_impossible': False}),
 Prediction(uid=358.0, iid=2797, r_ui=3.5, est=3.557267727120686, details={'was_impossible': False}),
 Prediction(uid=614.0, iid=33679, r_ui=4.0, est=3.8532757409895035, details={'was_impossible': False}),
 Prediction(uid=50.0, iid=2150, r_ui=4.0, est=3.034707980606413, details={'was_impossible': False}),
 Prediction(uid=277.0, iid=59850, r_ui=3.0, est=3.3439800691990835, details={'was_impossible': False}),
 Prediction(uid=632.0, iid=5452, r_ui=3.0, est=2.705184443323815, details={'was_impossible': False}),
 Prediction(uid=614.0, iid=99114, r_ui=5.0, est=4.6358910218273675, details={'was_impossible': False}),
 Prediction(uid=627.0, iid=4467, r_ui=4.0, est=3.635813629319795, details={'was_impossible': False}),
 Prediction(uid=402.0, iid=1027, r_ui=2.5, est=2.845721720119055, details={'was_impossible': False}),
 Prediction(uid=122.0, iid=2683, r_ui=3.0, est=3.2716545168798317, details={'was_impossible': False}),
 Prediction(uid=76.0, iid=3578, r_ui=4.0, est=4.159437069704201, details={'was_impossible': False}),
 Prediction(uid=62.0, iid=1285, r_ui=2.0, est=2.7683736312135268, details={'was_impossible': False}),
 Prediction(uid=458.0, iid=1394, r_ui=4.0, est=3.75178344382166, details={'was_impossible': False}),
 Prediction(uid=85.0, iid=2949, r_ui=3.0, est=3.890176692719926, details={'was_impossible': False}),
 Prediction(uid=236.0, iid=16, r_ui=3.0, est=3.728216659273381, details={'was_impossible': False}),
 Prediction(uid=607.0, iid=344, r_ui=3.0, est=2.6039888709317083, details={'was_impossible': False}),
 Prediction(uid=309.0, iid=4638, r_ui=2.0, est=2.302638754226461, details={'was_impossible': False}),
 Prediction(uid=451.0, iid=1967, r_ui=3.5, est=4.023764385547836, details={'was_impossible': False}),
 Prediction(uid=610.0, iid=33794, r_ui=4.0, est=3.5354494599034605, details={'was_impossible': False}),
 Prediction(uid=275.0, iid=32151, r_ui=3.0, est=3.418981770901322, details={'was_impossible': False}),
 Prediction(uid=655.0, iid=2797, r_ui=4.5, est=3.7428785425946245, details={'was_impossible': False}),
 Prediction(uid=501.0, iid=1219, r_ui=4.0, est=3.9250857916944604, details={'was_impossible': False}),
 Prediction(uid=389.0, iid=8368, r_ui=5.0, est=4.4413790135213596, details={'was_impossible': False}),
 Prediction(uid=592.0, iid=858, r_ui=5.0, est=4.745260041374655, details={'was_impossible': False}),
 Prediction(uid=461.0, iid=6966, r_ui=4.0, est=3.210571964254711, details={'was_impossible': False}),
 Prediction(uid=224.0, iid=78499, r_ui=3.5, est=3.8394720540496055, details={'was_impossible': False}),
 Prediction(uid=184.0, iid=6539, r_ui=0.5, est=3.7702165341752343, details={'was_impossible': False}),
 Prediction(uid=412.0, iid=55290, r_ui=2.5, est=3.8673173267594585, details={'was_impossible': False}),
 Prediction(uid=244.0, iid=2087, r_ui=3.0, est=2.941028626157118, details={'was_impossible': False}),
 Prediction(uid=567.0, iid=1625, r_ui=3.0, est=3.6221315645538414, details={'was_impossible': False}),
 Prediction(uid=224.0, iid=43679, r_ui=2.0, est=3.2876519167904887, details={'was_impossible': False}),
 Prediction(uid=443.0, iid=592, r_ui=4.0, est=3.603351217213135, details={'was_impossible': False}),
 Prediction(uid=409.0, iid=30810, r_ui=5.0, est=3.448711400500347, details={'was_impossible': False}),
 Prediction(uid=3.0, iid=45, r_ui=5.0, est=3.6309576050900927, details={'was_impossible': False}),
 Prediction(uid=501.0, iid=5618, r_ui=5.0, est=4.04499486604615, details={'was_impossible': False}),
 Prediction(uid=146.0, iid=2795, r_ui=4.0, est=4.0982999283071955, details={'was_impossible': False}),
 Prediction(uid=63.0, iid=1562, r_ui=2.5, est=2.0231723380025977, details={'was_impossible': False}),
 Prediction(uid=160.0, iid=1648, r_ui=4.0, est=3.7791937236184427, details={'was_impossible': False}),
 Prediction(uid=451.0, iid=70286, r_ui=5.0, est=4.100404486076721, details={'was_impossible': False}),
 Prediction(uid=589.0, iid=82167, r_ui=2.5, est=4.2617338480301905, details={'was_impossible': False}),
 Prediction(uid=299.0, iid=1258, r_ui=4.0, est=4.296063204833366, details={'was_impossible': False}),
 Prediction(uid=357.0, iid=2805, r_ui=2.0, est=2.164038985726063, details={'was_impossible': False}),
 Prediction(uid=569.0, iid=4034, r_ui=4.0, est=3.847620092687261, details={'was_impossible': False}),
 Prediction(uid=296.0, iid=1371, r_ui=3.5, est=3.223819718706765, details={'was_impossible': False}),
 Prediction(uid=331.0, iid=480, r_ui=2.0, est=3.528277348562458, details={'was_impossible': False}),
 Prediction(uid=207.0, iid=2174, r_ui=2.0, est=3.6267308094583117, details={'was_impossible': False}),
 Prediction(uid=225.0, iid=454, r_ui=4.0, est=4.004598536479457, details={'was_impossible': False}),
 Prediction(uid=382.0, iid=62293, r_ui=4.0, est=3.7424819903465694, details={'was_impossible': False}),
 Prediction(uid=423.0, iid=2710, r_ui=3.0, est=2.671389424792333, details={'was_impossible': False}),
 Prediction(uid=413.0, iid=96737, r_ui=4.5, est=3.5985422907544544, details={'was_impossible': False}),
 Prediction(uid=114.0, iid=4643, r_ui=3.5, est=2.5955403499668415, details={'was_impossible': False}),
 Prediction(uid=133.0, iid=587, r_ui=3.0, est=2.977629017337528, details={'was_impossible': False}),
 Prediction(uid=405.0, iid=6874, r_ui=4.0, est=4.180097786428879, details={'was_impossible': False}),
 Prediction(uid=629.0, iid=2300, r_ui=2.5, est=3.641185392523868, details={'was_impossible': False}),
 Prediction(uid=657.0, iid=1690, r_ui=2.5, est=2.726168484391948, details={'was_impossible': False}),
 Prediction(uid=614.0, iid=6708, r_ui=4.5, est=4.488473424899838, details={'was_impossible': False}),

In [115]:
df[df["movieId"] == 1006].head(1)

,userId,movieId,rating,timestamp,title,(no genres listed),Action,Adventure,Animation,Children,...,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year
25059,140.0,1006,2.0,850121331.0,"Chamber, The",0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1996

In [117]:
pd.set_option('display.max_columns', None)

# Mostrar la fila 25059
df.iloc[25059:25060]

,userId,movieId,rating,timestamp,title,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year
25059,140.0,1006,2.0,850121331.0,"Chamber, The",0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1996

In [122]:
df[(df["userId"] == 140.0) & (df["Drama"] == 1) & (df["movieId"] == 1006)]

,userId,movieId,rating,timestamp,title,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year
25059,140.0,1006,2.0,850121331.0,"Chamber, The",0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1996