In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import optuna
from surprise import Dataset, Reader, KNNBasic, SVD, accuracy
from surprise.model_selection import train_test_split as train_test_split_surprise
from surprise.model_selection import cross_validate
from surprise.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split as train_test_split_sklearn

C:\Users\JWinn01\AppData\Roaming\Python\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
point = (
    '../data/raw/movies.csv'
)
datos_movies = pd.read_csv(point, sep=',')
datos_movies.head(3)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance

In [4]:
point = (
    '../data/raw/ratings.csv'
)
datos_ratings = pd.read_csv(point, sep=',')
datos_ratings.head(3)

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828

In [5]:
datos_movies["genres"] = datos_movies["genres"].str.split("|")

df_exploded = datos_movies.explode('genres')
genre_dummies = pd.get_dummies(df_exploded['genres'])

df_combined = pd.concat([df_exploded[['movieId', 'title']], genre_dummies], axis=1)

In [6]:
df_final_movies = df_combined.groupby(['movieId', 'title'], as_index=False).sum()

In [7]:
df_final_movies

,movieId,title,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),0,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
4,5,Father of the Bride Part II (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62418,209157,We (2018),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
62419,209159,Window of the Soul (2001),0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
62420,209163,Bad Poems (2018),0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
62421,209169,A Girl Thing (2001),1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
62422,209171,Women of Devil's Island (1962),0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
df = merged_data = pd.merge(
    datos_ratings,
    df_final_movies,
    on="movieId",
    how="right"
)
df.head()

,userId,movieId,rating,timestamp,title,(no genres listed),Action,Adventure,Animation,Children,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,2.0,1,3.5,1.141416e+09,Toy Story (1995),0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,1,4.0,1.439472e+09,Toy Story (1995),0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,4.0,1,3.0,1.573944e+09,Toy Story (1995),0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,5.0,1,4.0,8.586259e+08,Toy Story (1995),0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,8.0,1,4.0,8.904925e+08,Toy Story (1995),0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [9]:
datos_ratings['userId'].nunique()

162541

In [10]:
df_colab  = datos_ratings.groupby('movieId')['rating'].mean().reset_index()

# opcional: renombrar la columna para mayor claridad
mean_ratings = df_colab.rename(columns={'rating': 'rating_medio'})

mean_ratings.head(20)

    movieId  rating_medio
0         1      3.893708
1         2      3.251527
2         3      3.142028
3         4      2.853547
4         5      3.058434
5         6      3.854909
6         7      3.363666
7         8      3.114583
8         9      2.992051
9        10      3.421458
10       11      3.657171
11       12      2.624566
12       13      3.333528
13       14      3.423489
14       15      2.719022
15       16      3.823707
16       17      3.948806
17       18      3.384351
18       19      2.642168
19       20      2.869922

In [11]:
X = mean_ratings
y = mean_ratings

In [12]:
#df_finito = df[['userId', 'movieId', 'rating']]
reader = Reader(rating_scale=(1, 5))
df_finito = Dataset.load_from_df(df[['userId', 'movieId', 'rating']], reader)

In [13]:
trainset, testset = train_test_split_surprise(df_finito, test_size=0.2, random_state=42)

In [14]:
df_finito

In [ ]:
# **Modelo KNN basado en ítems**
sim_options = {'name': 'cosine', 'user_based': True}  # Cambia user_based=True para KNN de usuarios
model = SVD(n_factors=50, n_epochs=20)  # Esta linea dedicada para ajustar el consumo de RAM
#model = KNNBasic(sim_options=sim_options) #Errores por tamaño de dataset
model.fit(trainset)

predictions = model.test(testset)#predecimos

In [ ]:
rmse = accuracy.rmse(predictions)
print(f'RMSE: {rmse}')

RMSE: nan
RMSE: nan

In [ ]:

user = str(96737)  # IDs deben ser strings en Surprise.... por alguna razón 
item = str(242)
pred = model.predict(user, item)
print(f'Predicción de usuario {user} para peli {item}: {pred.est}')

Predicción de usuario 196 para ítem 242: 5

In [ ]:
predictions

[Prediction(uid=128631.0, iid=96737, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=41761.0, iid=193, r_ui=1.5, est=5, details={'was_impossible': False}),
 Prediction(uid=121425.0, iid=2348, r_ui=2.0, est=5, details={'was_impossible': False}),
 Prediction(uid=17674.0, iid=1222, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=89415.0, iid=1396, r_ui=1.5, est=5, details={'was_impossible': False}),
 Prediction(uid=106481.0, iid=1204, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=12220.0, iid=180, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=nan, iid=185379, r_ui=nan, est=5, details={'was_impossible': False}),
 Prediction(uid=140711.0, iid=64957, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=33313.0, iid=1952, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=12979.0, iid=55363, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=86170.0, iid=899, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=117921.0, iid=4022, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=76369.0, iid=1041, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=142998.0, iid=5735, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=30240.0, iid=80489, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=150005.0, iid=4887, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=105236.0, iid=5782, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=78620.0, iid=4084, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=82160.0, iid=555, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=157085.0, iid=2997, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=106803.0, iid=1376, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=118719.0, iid=95558, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=75149.0, iid=4756, r_ui=2.0, est=5, details={'was_impossible': False}),
 Prediction(uid=158461.0, iid=382, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=50926.0, iid=1721, r_ui=2.5, est=5, details={'was_impossible': False}),
 Prediction(uid=56515.0, iid=1198, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=76706.0, iid=378, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=76330.0, iid=96610, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=92913.0, iid=4262, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=22521.0, iid=5952, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=47690.0, iid=849, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=139318.0, iid=5299, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=148813.0, iid=858, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=82142.0, iid=648, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=89622.0, iid=2985, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=156989.0, iid=224, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=32218.0, iid=1704, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=46604.0, iid=4701, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=64718.0, iid=1589, r_ui=1.0, est=5, details={'was_impossible': False}),
 Prediction(uid=162391.0, iid=474, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=120888.0, iid=1732, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=67892.0, iid=2571, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=60899.0, iid=8665, r_ui=2.0, est=5, details={'was_impossible': False}),
 Prediction(uid=48606.0, iid=595, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=1977.0, iid=6186, r_ui=2.5, est=5, details={'was_impossible': False}),
 Prediction(uid=152467.0, iid=2985, r_ui=2.0, est=5, details={'was_impossible': False}),
 Prediction(uid=39880.0, iid=6022, r_ui=2.5, est=5, details={'was_impossible': False}),
 Prediction(uid=58588.0, iid=89302, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=17051.0, iid=32, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=4835.0, iid=109487, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=103155.0, iid=4014, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=95253.0, iid=7234, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=37696.0, iid=7438, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=9398.0, iid=991, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=36618.0, iid=61697, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=106028.0, iid=7454, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=152637.0, iid=49396, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=56166.0, iid=65, r_ui=1.0, est=5, details={'was_impossible': False}),
 Prediction(uid=22517.0, iid=281, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=160970.0, iid=318, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=130429.0, iid=2, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=80433.0, iid=150, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=7735.0, iid=2683, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=67454.0, iid=118896, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=31980.0, iid=1446, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=40636.0, iid=81195, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=49529.0, iid=318, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=126995.0, iid=1206, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=96491.0, iid=6874, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=22620.0, iid=47997, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=41576.0, iid=415, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=144741.0, iid=2713, r_ui=1.5, est=5, details={'was_impossible': False}),
 Prediction(uid=49631.0, iid=95510, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=5222.0, iid=908, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=77727.0, iid=589, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=53082.0, iid=3617, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=24692.0, iid=5903, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=153496.0, iid=4372, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=76384.0, iid=8798, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=30792.0, iid=858, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=132747.0, iid=68205, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=123764.0, iid=2898, r_ui=2.0, est=5, details={'was_impossible': False}),
 Prediction(uid=39259.0, iid=4865, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=62290.0, iid=57532, r_ui=2.5, est=5, details={'was_impossible': False}),
 Prediction(uid=60613.0, iid=231, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=96776.0, iid=12, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=158564.0, iid=2054, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=162334.0, iid=4489, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=80866.0, iid=541, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=120136.0, iid=6753, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=112030.0, iid=507, r_ui=2.0, est=5, details={'was_impossible': False}),
 Prediction(uid=23444.0, iid=8360, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=162271.0, iid=100581, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=79982.0, iid=1230, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=32148.0, iid=1196, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=33961.0, iid=3629, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=29084.0, iid=64969, r_ui=1.5, est=5, details={'was_impossible': False}),
 Prediction(uid=57643.0, iid=6001, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=53015.0, iid=79848, r_ui=2.0, est=5, details={'was_impossible': False}),
 Prediction(uid=59665.0, iid=3524, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=145821.0, iid=132660, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=120663.0, iid=2469, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=71545.0, iid=5078, r_ui=2.0, est=5, details={'was_impossible': False}),
 Prediction(uid=138517.0, iid=4022, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=104842.0, iid=110, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=23497.0, iid=2716, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=162498.0, iid=2696, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=14561.0, iid=350, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=25752.0, iid=1196, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=137172.0, iid=1393, r_ui=2.5, est=5, details={'was_impossible': False}),
 Prediction(uid=3.0, iid=83613, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=26937.0, iid=6564, r_ui=1.0, est=5, details={'was_impossible': False}),
 Prediction(uid=77736.0, iid=4226, r_ui=0.5, est=5, details={'was_impossible': False}),
 Prediction(uid=8700.0, iid=1120, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=109462.0, iid=1257, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=136874.0, iid=151, r_ui=2.0, est=5, details={'was_impossible': False}),
 Prediction(uid=54862.0, iid=31658, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=20957.0, iid=87430, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=87671.0, iid=480, r_ui=0.5, est=5, details={'was_impossible': False}),
 Prediction(uid=26231.0, iid=516, r_ui=2.0, est=5, details={'was_impossible': False}),
 Prediction(uid=92504.0, iid=3827, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=84584.0, iid=2205, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=105520.0, iid=4641, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=38559.0, iid=44199, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=139638.0, iid=1690, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=92557.0, iid=84248, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=96344.0, iid=116797, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=154814.0, iid=77561, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=158354.0, iid=3500, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=150029.0, iid=139644, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=22779.0, iid=54997, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=94152.0, iid=1089, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=29608.0, iid=1391, r_ui=1.0, est=5, details={'was_impossible': False}),
 Prediction(uid=20179.0, iid=144964, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=141853.0, iid=1573, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=65646.0, iid=51077, r_ui=1.0, est=5, details={'was_impossible': False}),
 Prediction(uid=91450.0, iid=1584, r_ui=2.5, est=5, details={'was_impossible': False}),
 Prediction(uid=21701.0, iid=65230, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=31547.0, iid=3018, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=69349.0, iid=318, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=108992.0, iid=2406, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=32462.0, iid=45672, r_ui=2.0, est=5, details={'was_impossible': False}),
 Prediction(uid=15700.0, iid=1356, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=28182.0, iid=3793, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=104717.0, iid=3785, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=65001.0, iid=1033, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=110831.0, iid=2058, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=74166.0, iid=429, r_ui=0.5, est=5, details={'was_impossible': False}),
 Prediction(uid=110872.0, iid=89, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=81109.0, iid=2598, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=16908.0, iid=2088, r_ui=2.0, est=5, details={'was_impossible': False}),
 Prediction(uid=143091.0, iid=2167, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=152875.0, iid=110730, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=150079.0, iid=56587, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=41657.0, iid=86911, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=154069.0, iid=426, r_ui=1.0, est=5, details={'was_impossible': False}),
 Prediction(uid=68817.0, iid=500, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=66447.0, iid=590, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=118065.0, iid=3269, r_ui=1.0, est=5, details={'was_impossible': False}),
 Prediction(uid=84793.0, iid=2726, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=18677.0, iid=1097, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=116455.0, iid=81564, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=149394.0, iid=915, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=98273.0, iid=919, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=108841.0, iid=141, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=24655.0, iid=8874, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=82892.0, iid=88163, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=42155.0, iid=733, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=12030.0, iid=110, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=129595.0, iid=225, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=153489.0, iid=3211, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=83567.0, iid=1995, r_ui=2.0, est=5, details={'was_impossible': False}),
 Prediction(uid=27760.0, iid=1247, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=76635.0, iid=1280, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=142344.0, iid=1197, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=155791.0, iid=4370, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=78187.0, iid=3081, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=4711.0, iid=110730, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=134299.0, iid=3125, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=49100.0, iid=8874, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=47674.0, iid=6377, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=136962.0, iid=3793, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=72337.0, iid=3712, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=11701.0, iid=1641, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=146127.0, iid=1203, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=64472.0, iid=32, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=106044.0, iid=2502, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=28344.0, iid=467, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=36787.0, iid=290, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=114438.0, iid=179819, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=43370.0, iid=6377, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=4389.0, iid=4857, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=101311.0, iid=595, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=98547.0, iid=5014, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=88455.0, iid=2752, r_ui=2.0, est=5, details={'was_impossible': False}),
 Prediction(uid=43251.0, iid=2377, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=150468.0, iid=1202, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=28077.0, iid=145, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=35620.0, iid=8360, r_ui=2.5, est=5, details={'was_impossible': False}),
 Prediction(uid=152107.0, iid=26831, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=24906.0, iid=1227, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=57548.0, iid=2728, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=104911.0, iid=8957, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=115822.0, iid=185, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=154785.0, iid=30825, r_ui=0.5, est=5, details={'was_impossible': False}),
 Prediction(uid=153762.0, iid=1282, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=86462.0, iid=90647, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=75859.0, iid=457, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=23202.0, iid=368, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=152699.0, iid=7147, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=47428.0, iid=4018, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=128251.0, iid=57669, r_ui=4.5, est=5, details={'was_impossible': False}),
 Prediction(uid=67419.0, iid=344, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=19965.0, iid=33794, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=127375.0, iid=4816, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=138617.0, iid=4545, r_ui=3.5, est=5, details={'was_impossible': False}),
 Prediction(uid=23632.0, iid=4369, r_ui=5.0, est=5, details={'was_impossible': False}),
 Prediction(uid=75111.0, iid=31685, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=13935.0, iid=3697, r_ui=3.0, est=5, details={'was_impossible': False}),
 Prediction(uid=4313.0, iid=949, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=112247.0, iid=316, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=77178.0, iid=109848, r_ui=1.0, est=5, details={'was_impossible': False}),
 Prediction(uid=101729.0, iid=60756, r_ui=2.5, est=5, details={'was_impossible': False}),
 Prediction(uid=106643.0, iid=59315, r_ui=4.0, est=5, details={'was_impossible': False}),
 Prediction(uid=68919.0, iid=32, r_ui=4.5, est=5, details={'was_impossible': False}),