In [57]:
import pandas as pd

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity

In [46]:
movies = pd.read_csv('../../datos/movie_recomendations/movies_cleaned.csv')
movies

,movieId,title,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,...,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year
0,1,Toy Story (1995),0,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1995.0
1,2,Jumanji (1995),0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1995.0
2,3,Grumpier Old Men (1995),0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,1995.0
3,4,Waiting to Exhale (1995),0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,1995.0
4,5,Father of the Bride Part II (1995),0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1995.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57233,209155,Santosh Subramaniam (2008),1,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,2008.0
57234,209157,We (2018),0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,2018.0
57235,209159,Window of the Soul (2001),0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,2001.0
57236,209163,Bad Poems (2018),0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,2018.0
57237,209171,Women of Devil's Island (1962),1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1962.0

In [47]:
movies = movies.sample(5000)
movies.reset_index(inplace=True)
movies.drop(columns=['index'], inplace=True)
movies

,movieId,title,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,...,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year
0,4370,A.I. Artificial Intelligence (2001),0,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,2001.0
1,152415,The Weapon (1957),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1957.0
2,160596,Les Tuche 2 : Le Rêve Américain (2016),0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,2016.0
3,125269,Touching Home (2008),0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,2008.0
4,162100,"The Fjällbacka Murders: The Sea Gives, the Sea...",0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,2013.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,176771,Surviving Evil (2009),1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,2009.0
4996,32128,Blackball (2003),0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,2003.0
4997,163745,The Kid (1997),1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1997.0
4998,122914,Avengers: Infinity War - Part II (2019),1,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,2019.0
4999,3030,Yojimbo (1961),1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1961.0

In [48]:
def recommend_movies(movie_title, df, similarity_matrix, top_n=5):
    # Encontrar el índice de la película dada
    idx = df[df['title'] == movie_title].index[0]
    
    # Obtener similitudes con otras películas
    sim_scores = list(enumerate(similarity_matrix[idx]))
    
    # Ordenar por mayor similitud (excluyendo la propia película)
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:top_n+1]
    
    # Obtener los títulos recomendados
    recommended_indices = [i[0] for i in sim_scores]
    return df['title'].iloc[recommended_indices]

In [49]:
# Normalizar el año
#scaler = MinMaxScaler()
#movies['year_scaled'] = scaler.fit_transform(movies[['year']])

In [50]:
genre_columns = movies.columns[2:-1]
content_features = movies[genre_columns].copy()
#content_features['year'] = movies['year_scaled']

# Matriz de similitud (generos)
similarity_matrix = cosine_similarity(content_features)

In [51]:
similarity_matrix

array([[1.        , 0.        , 0.        , ..., 0.33333333, 0.66666667,
        0.40824829],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.33333333, 0.        , 0.        , ..., 1.        , 0.33333333,
        0.40824829],
       [0.66666667, 0.        , 0.        , ..., 0.33333333, 1.        ,
        0.81649658],
       [0.40824829, 0.        , 0.        , ..., 0.40824829, 0.81649658,
        1.        ]])

In [55]:
year_filtrado = 2000
recomendaciones = recommend_movies("The Weapon (1957)", movies, similarity_matrix)
#recomendaciones = recommend_movies("Toy Story (1995)", movies, similarity_matrix)
#recomendaciones_filtradas = recomendaciones[recomendaciones['year'] >= year_filtrado]

In [56]:
print(f'Recomendaciones: ')
display(recomendaciones)
#display(f'Recomendaciones por Año ({year_filtrado}): {recomendaciones}')

Recomendaciones:

27       Shadow Run (1998)
64         Deadrise (2011)
109      De Premier (2016)
162       The Cabin (2018)
207    Perfect Plan (2010)
Name: title, dtype: object