In [47]:
import pandas as pd

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
movies = pd.read_csv('../../datos/movie_recomendations/movies_cleaned.csv')
movies

,movieId,title,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,...,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year
0,1,Toy Story (1995),0,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1995.0
1,2,Jumanji (1995),0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1995.0
2,3,Grumpier Old Men (1995),0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,1995.0
3,4,Waiting to Exhale (1995),0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,1995.0
4,5,Father of the Bride Part II (1995),0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1995.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57356,209155,Santosh Subramaniam (2008),1,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,2008.0
57357,209157,We (2018),0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,2018.0
57358,209159,Window of the Soul (2001),0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,2001.0
57359,209163,Bad Poems (2018),0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,2018.0
57360,209171,Women of Devil's Island (1962),1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1962.0

In [49]:
def recommend_movies(movie_title, df, similarity_matrix, top_n=5):
    # Encontrar el índice de la película dada
    idx = df[df['title'] == movie_title].index[0]
    
    # Obtener similitudes con otras películas
    sim_scores = list(enumerate(similarity_matrix[idx]))
    
    # Ordenar por mayor similitud (excluyendo la propia película)
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:top_n+1]
    
    # Obtener los títulos recomendados
    recommended_indices = [i[0] for i in sim_scores]
    return df['title'].iloc[recommended_indices]

In [50]:
movies[movies['year'].isna()][['movieId', 'title', 'year']]

       movieId                                        title  year
15036    79607      Millions Game, The (Das Millionenspiel)   NaN
26300   126438               Two: The Story of Roman & Nyro   NaN
26874   128612                                   Body/Cialo   NaN
26919   128734                                Polskie gówno   NaN
27211   129697                      La vendetta dei barbari   NaN
...        ...                                          ...   ...
56582   206198                           The Night Bulletin   NaN
56869   207135                              The Evil Inside   NaN
56895   207199                       Along Came the Devil 2   NaN
56945   207337                      Liberia: An Uncivil War   NaN
57248   208597  Punk the Capital: Building a Sound Movement   NaN

[146 rows x 3 columns]

In [51]:
# Normalizar el año
scaler = MinMaxScaler()
#movies['year_scaled'] = scaler.fit_transform(movies[['year']])

In [52]:
genre_columns = movies.columns[2:-1]
content_features = movies[genre_columns].copy()
#content_features['year'] = movies['year_scaled']

# Matriz de similitud (generos)
similarity_matrix = cosine_similarity(content_features)

In [53]:
similarity_matrix

array([[1.        , 0.77459667, 0.31622777, ..., 0.        , 0.31622777,
        0.25819889],
       [0.77459667, 1.        , 0.        , ..., 0.        , 0.        ,
        0.33333333],
       [0.31622777, 0.        , 1.        , ..., 0.        , 0.5       ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.31622777, 0.        , 0.5       , ..., 0.        , 1.        ,
        0.40824829],
       [0.25819889, 0.33333333, 0.        , ..., 0.        , 0.40824829,
        1.        ]], shape=(57361, 57361))

In [55]:
year_filtrado = 2000
recomendaciones = recommend_movies("Toy Story (1995)", movies, similarity_matrix)
#recomendaciones_filtradas = recomendaciones[recomendaciones['year'] >= year_filtrado]

In [57]:
print(f'Recomendaciones: ')
display(recomendaciones)
#display(f'Recomendaciones por Año ({year_filtrado}): {recomendaciones}')

Recomendaciones:

2203                                       Antz (1998)
3021                                Toy Story 2 (1999)
3653    Adventures of Rocky and Bullwinkle, The (2000)
3912                  Emperor's New Groove, The (2000)
4780                             Monsters, Inc. (2001)
Name: title, dtype: object